version: '3.2'

services:

  db:
    image: postgres:14
    hostname: db
    environment:
      POSTGRES_DB: financialApp
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
    - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - 8080:8080